### ISSUE TITLE
pgagroal-cli segfault

### ISSUE THREAD

**Issue by will** [agroal/pgagroal#140]
**Describe the bug**

Segfault in pgagroal-cli with no arguments.

**To Reproduce**

```
[~]$ pgagroal-cli
Segmentation fault (core dumped)
[~]$ sudo -u pgagroal pgagroal-cli
Segmentation fault
```
**Version**

1.2.0

**PostgreSQL**

13.2

**libev**

4.24-6.el8

**OpenSSL**

1.1.1g

**Access method**

n/a

**OS**

CentOS Linux release 8.3.2011

**ulimit**

```
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 30415
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 30415
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Configuration**

Can you provide the configuration pgagroal ?

* pgagroal.conf

```
[pgagroal]
host = 0.0.0.0
port = 5431

log_type = syslog
log_level = debug1

pipeline = transaction
idle_timeout = 0
blocking_timeout = 0
validation = foreground

max_connections = 100
validation = off
unix_socket_dir = /tmp/

tls = on
tls_cert_file = /dat/13/data/server.crt
tls_key_file  = /dat/13/data/server.key

[primary]
host = localhost
port = 5432
```

* pgagroal_hba.conf

```
hostssl all      all   all      all
```

* pgagroal_databases.conf
none
* pgagroal_users.conf
none

**Debug logs**

```
Core was generated by `pgagroal-cli'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f3dcf9e1d52 in __strcmp_avx2 () from /usr/lib64/libc.so.6
Missing separate debuginfos, use: yum debuginfo-install glibc-2.28-127.el8.x86_64 libblkid-2.32.1-24.el8.x86_64 libcap-2.26-4.el8.x86_64 libev-4.24-6.el8.x86_64 libgcc-8.3.1-5.1.el8.x86_64 libgcrypt-1.8.5-4.el8.x86_64 libgpg-error-1.31-1.el8.x86_64 libmount-2.32.1-24.el8.x86_64 libselinux-2.9-4.el8_3.x86_64 libuuid-2.32.1-24.el8.x86_64 lz4-libs-1.8.3-2.el8.x86_64 openssl-libs-1.1.1g-12.el8_3.x86_64 pcre2-10.32-2.el8.x86_64 systemd-libs-239-41.el8_3.1.x86_64 xz-libs-5.2.4-3.el8.x86_64 zlib-1.2.11-16.el8_2.x86_64
(gdb) bt
#0  0x00007f3dcf9e1d52 in __strcmp_avx2 () from /usr/lib64/libc.so.6
#1  0x0000560f056019fa in main (argc=<optimized out>, argv=0x7fff19cd4ab8)
    at /usr/src/debug/pgagroal-1.2.0-1Crunchy.el8.x86_64/src/cli.c:305
(gdb) list
117	   printf("  cancel-shutdown          Cancel the graceful shutdown\n");
118	   printf("  status                   Status of pgagroal\n");
119	   printf("  details                  Detailed status of pgagroal\n");
120	   printf("  switch-to                Switch to another primary\n");
121	   printf("  reload                   Reload the configuration\n");
122	   printf("  reset                    Reset the Prometheus statistics\n");
123	   printf("  reset-server             Reset the state of a server\n");
124	   printf("\n");
125	   printf("pgagroal: %s\n", PGAGROAL_HOMEPAGE);
126	   printf("Report bugs: %s\n", PGAGROAL_ISSUES);
(gdb) f 1
#1  0x0000560f056019fa in main (argc=<optimized out>, argv=0x7fff19cd4ab8)
    at /usr/src/debug/pgagroal-1.2.0-1Crunchy.el8.x86_64/src/cli.c:305
305	      else if (!strcmp("enable", argv[argc - 1]) || !strcmp("enable", argv[argc - 2]))
(gdb) list
300	      else if (!strcmp("flush-all", argv[argc - 1]))
301	      {
302	         mode = FLUSH_ALL;
303	         action = ACTION_FLUSH;
304	      }
305	      else if (!strcmp("enable", argv[argc - 1]) || !strcmp("enable", argv[argc - 2]))
306	      {
307	         action = ACTION_ENABLEDB;
308	         if (!strcmp("enable", argv[argc - 1]))
309	         {
(gdb) p argc
$3 = <optimized out>
(gdb) p argv
$4 = (char **) 0x7fff19cd4ab8
(gdb) printf "%s\n", *argv
pgagroal-cli
(gdb)
```

**Comment by jesperpedersen** [comment]
Thanks Will ! Fixed.
